#!/bin/sh
set -e

# Xcode Cloud runs this after cloning the repo and before dependency
# resolution/build. The .xcodeproj is generated by XcodeGen and isn't
# committed to git (see project.yml), and the full AirDash build needs
# Go to compile libwg-go.a (WireGuardGoBridge) — neither is present on
# a fresh Xcode Cloud image, so both are set up here.

cd "$CI_PRIMARY_REPOSITORY_PATH"

# The WireGuardKit submodule is required for the full build (AirDashTunnel).
git submodule update --init --recursive

brew install xcodegen go

xcodegen generate
